### PR TITLE
fixes issue #73

### PR DESCRIPTION
**Pull request by rillip3**
This passed tests locally, but failed circle because of environment foo. Reopening here for automated testing

### CODE REVIEW

**Comment by rillip3** [comment]
Is there any access to these logs or to get access to this machine? I haven't been able to duplicate this failure in hot tests

**Comment by rs-randallburt** [comment]
@rillip3 https://circle-artifacts.com/gh/rackspace-orchestration-templates/lamp/917/artifacts/0/tmp/circle-artifacts.XNEZc0M/104.239.228.75/run_chef.log

Looks like a play failed in installing mysql libs with a conflict:

```bash
msg: Error: mysql55-libs conflicts with mysql-libs-5.1.73-5.el6_6.x86_64
```
We are also looking into this with the automation team.

**Comment by rs-randallburt** [comment]
@rillip3  also, this only fails when using a managed account. Using a non-managed account works as far as we can tell.

**Comment by vikomall** [comment]
@rs-randallburt  I just tested and this template works fine with redhat OS.

**Comment by rillip3** [comment]
Yeah I've been seeing some of those failures as well Randal, but on a retry, it's worked fine. I brought it up to Servermill earlier in the week because the one I had seemed to have exited yum uncleanly while trying to install drive client, but I haven't been able to consistently reproduce the problem. The code base does execute on a managed account without issue, but there's some kind of unpredictable interference coming in with yum somewhere.

**Pull request merged**
