### PR TITLE
fixes issue #73

### PR DESCRIPTION
**Pull request by rillip3**
This should fix the issues we've been having with monitoring alerts. This passed my hot tests locally, but we've been having some unrelated failures due to yum not removing dependencies for mysql 5.1 properly. A retry fixes those if they happen.

### CODE REVIEW

**Comment by rillip3** [comment]
'Tool requires either OS_PASSWORD or OS_AUTH_TOKEN to be set.' envshuffle hot test --ci-parallel returned exit code 1' I think this just means that I'm missing permission to the environment for testing.

**Comment by brint** [comment]
@rillip3 Push the branch to the `rackspace-orchestration-templates/lamp` repo. By default CircleCI won't put the environment variables in place for PR's from forks. It's a security thing, otherwise in a PR, a user could just put in a bunch of print statements to pull sensitive info.

**Comment by rillip3** [comment]
So... to get checks to run we push to master? No prs any time? That seems... risky?

**Comment by chrishultin** [comment]
Philip,

Checks should work if you use any branch from the actual repo.  Don't make
any changes directly to master though.

**Comment by brint** [comment]
What @chrishultin said. Set this repo as a remote and create a branch to push up:

```
git remote add upstream git@github.com:rackspace-orchestration-templates/lamp.git
git fetch upstream
git checkout -b fix-73 upstream/master
git push upstream fix-73
```

**Comment by brint** [comment]
^ or something similar

**Comment by rillip3** [comment]
Thanks, reopened as instructed. Flow feels subobtimal for git though.

**Pull request closed without merging**
