### PR TITLE
Issue94

### PR DESCRIPTION
**Pull request by rillip3**
Adds in RHEL/Cent specific handling for systemd changes related to issue #94

### CODE REVIEW

**Comment by BeenzSyed** [comment]
HOT Tests Passed!

**Comment by BeenzSyed** [comment]
HOT Tests failed.

**Comment by BeenzSyed** [comment]
HOT Tests Passed!

**Comment by rscocicd** [comment]
Can one of the admins verify this patch?

**Comment by rillip3** [comment]
This has already been fixed in the new recipes at https://github.com/rackspace-orchestration-templates/ansible-roles/, closing.

**Pull request closed without merging**
